### ISSUE TITLE
Unicode Encode Error

### ISSUE THREAD

**Issue by omega303** [j2kun/imsdb_download_all_scripts#2]
I am getting the following error when running the file - download_all_scripts.py:-
python download_all_scripts.py     
                                                                                                                                                                              
fetching 10 Things I Hate About You Script.html                                                                                                                                                                    fetching 12 Script.html                                                                                                                                                                                            fetching 12 and Holding Script.html                                                                                                                                                                                fetching 12 Monkeys Script.html                                                                                                                                                                                    fetching 12 Years a Slave Script.html                                                                                                                                                                              fetching 127 Hours Script.html                                                                                                                                                                                     fetching 1492: Conquest of Paradise Script.html                                                                                                                                                                    fetching 15 Minutes Script.html                                                                                                                                                                                    fetching 17 Again Script.html                                                                                                                                                                                      fetching 187 Script.html                                                                                                                                                                                           fetching 2001: A Space Odyssey Script.html                                                                                                                                                                         fetching 2012 Script.html                                                                                                                                                                                          fetching 25th Hour Script.html                                                                                                                                                                                     fetching 30 Minutes or Less Script.html                                                                                                                                                                            fetching 42 Script.html                                                                                                                                                                                            Traceback (most recent call last):                                                                                                                                                                                   File "download_all_scripts.py", line 64, in                                                                                                                                                                  outfile.write(script)                                                                                                                                                                                            File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode                                                                                                             return codecs.charmap_encode(input,self.errors,encoding_table)[0]                                                                                                                                              UnicodeEncodeError: 'charmap' codec can't encode characters in position 5078-5079: character maps to

I would appreciate any help around the above.

**Comment by Alcyoal** [comment]
Hey, 
It has been a while but : 
Open download_all_scripts.py in a text editor, and replace : 

with open(os.path.join(SCRIPTS_DIR, title.strip('.html') + '.txt'), 'w')

by : 

with open(os.path.join(SCRIPTS_DIR, title.strip('.html') + '.txt'), 'w', encoding="utf-8")

It should fix your issue
